/**
 * APK provenance endpoint.
 *
 * Returns the provenance manifest for APKs pulled from donor devices.
 * Requires a valid Bearer API key (see auth/middleware.ts).
 *
 * The provenance.json is generated by tools/app_inventory/merge_csv_with_hashes.py
 * and is intentionally git-ignored to prevent inadvertent disclosure of device
 * identifiers. It is expected to be present at runtime (e.g. copied in CI from
 * a secrets store or regenerated on-demand).
 */

import { Router, type Request, type Response } from "express";
import { readFile } from "fs/promises";
import { join } from "path";

const router = Router();

const PROVENANCE_PATH = join(process.cwd(), "apks", "provenance.json");

router.get("/provenance", (_req: Request, res: Response) => {
  readFile(PROVENANCE_PATH, "utf8")
    .then((data) => {
      const parsed: unknown = JSON.parse(data);
      res.json(parsed);
    })
    .catch((err: NodeJS.ErrnoException) => {
      if (err.code === "ENOENT") {
        res.status(404).json({
          error: "Provenance manifest not found. Run tools/app_inventory/merge_csv_with_hashes.py to generate it.",
        });
      } else {
        res.status(500).json({ error: "Failed to read provenance manifest." });
      }
    });
});

export default router;
